[tools]
ruby = "latest"
php = "latest"
python = "3.14.5"
deno = "latest"
java = "latest"
scala = "2"
kotlin = "latest"
node = "latest"
clojure = "latest"
bun = "latest"

[settings]
auto_install = false
