framework:
  github: supranim/supranim
  version: 0.1

  build_deps:
    - openssl
    - libpcre3-dev
    - libevent-dev
    - pkg-config

  build_opts:
    - "--mm:arc"
    - "-d:webapp"
    - "-d:httpbench" # skip base middleware

  engines:
    default:
      command: /usr/src/app/server start . --port:3000

framework:
  engines:
    - default